- hosts: all
  roles:
    - role: prereq
      become: true
    - role: 'istvano.microk8s'
      vars:
        microk8s_plugins:
          metallb: 192.168.15.249-192.168.15.249  # Loadbalancer for your Kubernetes cluster
          dns: "{{ microk8s_dns_resolvers }}"     # CoreDNS
          kube-ovn: false                         # The feature rich Kube-OVN network fabric
          host-access: false                      # Allow Pods connecting to Host services smoothly
          ingress: false                          # Ingress controller for external access
          metrics-server: true                    # K8s Metrics Server for API access to service metrics
          rbac: true                              # Role-Based Access Control for authorisation
          hostpath-storage: true                  # Storage class; allocates storage from host directory
          registry: "size={{ registry_size }}"    # Private image registry exposed on localhost:32000
          dashboard: false                        # The Kubernetes dashboard
          ambassador: false                       # Ambassador API Gateway and Ingress
          cilium: false                           # SDN, fast with full network policy
          fluentd: false                          # Elasticsearch-Fluentd-Kibana logging and monitoring
          gpu: false                              # Automatic enablement of Nvidia CUDA
          helm: false                             # Helm 2 - the package manager for Kubernetes
          helm3: true                             # Helm 3 - Kubernetes package manager
          istio: false                            # Core Istio service mesh services
          jaeger: false                           # Kubernetes Jaeger operator with its simple config
          knative: false                          # The Knative framework on Kubernetes.
          kubeflow: false                         # Kubeflow for easy ML deployments
          linkerd: false                          # Linkerd is a service mesh for Kubernetes and other frameworks
          multus: false                           # Multus CNI enables attaching multiple network interfaces to pods
          prometheus: true                        # Prometheus operator for monitoring and logging
          traefik: true                           # another ingress
          portainer: false                        # Container management dashboard
          keda: false                             # Kubernetes Event-driven Autoscaling operator.
          kata: false                             # A secure container runtime with lightweight virtual machines
          openebs: true                           # openebs storage
          openfaas: false                         # serverless
          cert-manager: true                      # Certificate management for Kubernetes clusters
          community: true                         # Enables the community addons repository
          ha-cluster: true                        # Allows for high availability on clusters with at least three nodes.
