---
- name: Uninstall microk8s
  become: yes
  command: "snap remove --purge microk8s"
  changed_when: true

- name: Reload daemon_reload
  systemd:
    daemon_reload: yes

- name: Check if rc.local exists
  stat:
    path: /etc/rc.local
  register: rcfile

- name: Delete content & directory
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/var/log/*"